baseURL = "http://example.org/"
languageCode = "en-us"
title = "Starmodder"

enableEmoji = true
theme = "ananke"

[params]
custom_css = ["css/mdb.dark.min.css", "css/simple-lightbox.css"]
custom_js_header = [
  "/js/marked.min.js",
  "/js/purify.min.js",
  "/js/jquery-3.6.0.slim.min.js"
]
custom_js_footer = [
  "/js/mdb.min.js",
  "/js/simple-lightbox.min.js",
]

# From Ananke Theme
# DefaultContentLanguage = "en" 
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# SectionPagesMenu = "main" 
# enableRobotsTXT = true 
# googleAnalytics = "" 

# [languages]
# [languages.en]
# contentDir = "content/en"
# title = "Ananke"
# weight = 1
# # languageDirection = 'rtl' for Right-To-Left languages
# [languages.fr]
# contentDir = "content/fr"
# title = "Ananke Fr"
# weight = 2

# [sitemap]
# changefreq = "monthly"
# filename = "sitemap.xml"
# priority = 0.5

# [params]
# author = ""
# description = "The last theme you'll ever need. Maybe."
# favicon = ""
# site_logo = ""
# text_color = ""
# # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# background_color_class = "bg-black"
# recent_posts_number = 3

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
